<div class="ksolves-news">
	<?php $allnews = $this->getListNews() ?>
	<?php if($allnews && count($allnews)): ?>
		<?php foreach($allnews as $news): ?>
			<div class="ksg-news-list">
				<div class="ksg-news-title">
					<a href="#">
						<?php echo $news->getTitle() ?>
					</a>
					</div>
				<div class="ksg-news-time"><?php echo $news->getCreatedAt() ?></div>
				<div class="ksg-news-desc"><?php echo $news->getDescription() ?></div>
			</div>
		<?php endforeach; ?>
		
		<?php if($this->getPagerHtml()): ?>
			<?php echo $this->getPagerHtml(); ?>
		<?php endif; ?>
	<?php else: ?>
		<div class="ksolves-no-records">
			<?php echo __('News not available'); ?>
		</div>
	<?php endif; ?>
</div>
