<!-- <form  class="form" id="my-form" method="post" data-mage-init='{"validation":{"rules": {"field-4": {"required":true}}}}'>
    <fieldset class="fieldset">
        <div class="field name required">
            <label class="label" for="field-1"><span>(url-key)</span></label>
            <div class="control">
                <input name="url-key" id="field-1" title="Field 1" value=""  class="input-text" type="text" data-validate='{"required":true, "url": true}'/>
            </div>
        </div>
        <div class="field name required">
            <label class="label" for="field-2"><span>(name)</span></label>
            <div class="control">
                <input name="name" id="field-2" title="Field 2" value="" class="input-text" type="text" required="true"/>
            </div>
        </div>
        <div class="field name required">
            <label class="label" for="field-3"><span>(tags)</span></label>
            <div class="control">
                <input name="tags" id="field-3" title="Field 3" value="" type="text" class="input-text required-entry"/>
            </div>
        </div>
        <div class="field name required">
            <label class="label" for="field-4"><span>(post-content)</span></label>
            <div class="control">
                <input name="post-content" id="field-4" title="Field 4" value="" class="input-text required-entry" type="text"/>
            </div>
        </div>
        <div class="field name required">
            <label class="label" for="field-5"><span>(status)</span></label>
            <div class="control">
                <input name="status" id="field-5" title="Field 5" value="" class="input-text required-entry" type="text"/>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="Submit" class="action submit primary">
                <span>Submit</span>
            </button>
        </div>
    </div>
</form>

 -->

 <?php

               $result = $block->getEditRecord();

               echo $result;

 ?>