<head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>

   <div class="control">
                <input name="searchid" id="quick-search" class="input-text" type="text" placeholder="Search Ksolves Row By Row Name" />
   </div>
  

</br>

<div id="result"></div>

</br>
</br>

<?php if ($block->getPagerHtml()): ?>
    <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
<?php endif ?>
<!-- <?php $gridrecords = $block->getCustomCollection(); ?>
<?php if ($gridrecords && count($gridrecords)): ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?php echo __('Table Data Record') ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col id"><?php echo __('ID') ?></th>
                <th scope="col" class="col title"><?php echo __('Name') ?></th>
                <th scope="col" class="col title"><?php echo __('Created At') ?></th>
                <th scope="col" class="col title"><?php echo __('Updated At') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach ($gridrecords as $gridrecord): ?>
                <tr>
                    <td data-th="<?= $block->escapeHtml(__('ID')) ?>" class="col id">
                        <?php echo $gridrecord->getData('post_id'); ?>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Name')) ?>"
                        class="col title"><?php echo $gridrecord->getData('name'); ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Created At')) ?>" class="col title">
                            <?php echo $gridrecord->getData('created_at') ?>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Updated At')) ?>" class="col title">
                            <?php echo $gridrecord->getData('updated_at') ?>
                    </td>
                    
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?php echo __('No any record.'); ?></span></div>
<?php endif ?>
 -->
  <div style="width:900px; margin:0 auto;">
        
    
 <table>
     <tr>
          <th>Id</th>
          <th>Name</th>
          <th>Created At</th>
          <th>Updated At</th>
          <th colspan="3">Action</th>
     </tr>
 
     <?php
          $collection = $block->getCustomCollection();
          foreach($collection as $item){
     ?>
     <tr>
          <td><?php echo $item->getData('post_id'); ?></td>
          <td><?php echo $item->getData('name'); ?></td>
          <td><?php echo $item->getData('created_at'); ?></td>
          <td><?php echo $item->getData('updated_at'); ?></td>

          <td><a class="action primary" href="<?php echo $block->getUrl('helloworld/index/insert'); ?>">Add Record</a></td>

          <td><a class="action primary" href="<?php echo $block->getUrl('helloworld/index/edit').'id/'.$item->getData('post_id'); ?>">Edit</a></td>

          <td><a class="action primary" href="<?php echo $block->getUrl('helloworld/index/delete').'?id='.$item->getData('post_id');?> ">Delete</a></td>
         
     </tr>
     <?php } ?>
</table>
</div>

</br>
</br>
<?php if ($block->getPagerHtml()): ?>
    <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
<?php endif ?>


<script>
    require(
        [
            'jquery'
        ],
        function (
            $
        ) {
            $('#quick-search').keyup(function () {
                var search_text = $("#quick-search").val();
                console.log(search_text);
                $.ajax({
                    url: '<?= $block->getBaseUrl() . 'helloworld/index/ajax'; ?>',
                    type: 'POST',
                    data: {'search_text': search_text},
                    showLoader: false,
                    success: function (response) {
                        if (response)
                            $('#result').html(response);
                        else
                            $('#result').html('');
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        var errorMsg = 'Ajax request failed: ' + xhr.responseText;
                        $('#result').text(errorMsg);
                    }
                });
            });
        });

</script>



 